apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: microblogging-virtualserver
  namespace: microblogging
spec:
  host: microblogging.local
  upstreams:
  - name: tweets-read
    service: tweets-read-service
    port: 80
  - name: tweets-write
    service: tweets-write-service
    port: 80
  - name: feed
    service: feed-service
    port: 80
  - name: users
    service: users-service
    port: 80
  - name: analytics
    service: analytics-service
    port: 80
  - name: docsify
    service: docsify
    port: 80
  - name: swagger-ui
    service: swagger-ui
    port: 80
  routes:
  - path: /api/tweets/
    matches:
      - conditions:
          - variable: $request_method
            value: "~^(POST|PUT|DELETE)$"
        action:
          proxy:
            upstream: tweets-write
            rewritePath: /
      - conditions:
          - variable: $request_method
            value: GET
        action:
          proxy:
            upstream: tweets-read
            rewritePath: /
    action:
      proxy:
        upstream: tweets-read
        rewritePath: /
  - path: /api/feed/
    action:
      proxy:
        upstream: feed
        rewritePath: /      
  - path: /api/users/
    action:
      proxy:
        upstream: users
        rewritePath: /
  - path: /api/analytics/
    action:
      proxy:
        upstream: analytics
        rewritePath: /
  - path: /docs/
    action:
      proxy:
        upstream: docsify
        rewritePath: /
  - path: /swagger/
    action:
      proxy:
        upstream: swagger-ui
        rewritePath: /
  - path: /
    action:
      proxy:
        upstream: docsify
        rewritePath: /
