// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=feed
//

// Package feed is a generated GoMock package.
package feed

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetUserTimeline mocks base method.
func (m *MockService) GetUserTimeline(ctx context.Context, userID string, limit, offset int) (*TimelineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTimeline", ctx, userID, limit, offset)
	ret0, _ := ret[0].(*TimelineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTimeline indicates an expected call of GetUserTimeline.
func (mr *MockServiceMockRecorder) GetUserTimeline(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTimeline", reflect.TypeOf((*MockService)(nil).GetUserTimeline), ctx, userID, limit, offset)
}
