// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=analytics
//

// Package analytics is a generated GoMock package.
package analytics

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteUserAnalytics mocks base method.
func (m *MockService) DeleteUserAnalytics(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAnalytics", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAnalytics indicates an expected call of DeleteUserAnalytics.
func (mr *MockServiceMockRecorder) DeleteUserAnalytics(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAnalytics", reflect.TypeOf((*MockService)(nil).DeleteUserAnalytics), ctx, userID)
}

// GetAllUserAnalytics mocks base method.
func (m *MockService) GetAllUserAnalytics(ctx context.Context) ([]*UserAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserAnalytics", ctx)
	ret0, _ := ret[0].([]*UserAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserAnalytics indicates an expected call of GetAllUserAnalytics.
func (mr *MockServiceMockRecorder) GetAllUserAnalytics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserAnalytics", reflect.TypeOf((*MockService)(nil).GetAllUserAnalytics), ctx)
}

// GetUserAnalytics mocks base method.
func (m *MockService) GetUserAnalytics(ctx context.Context, userID string) (*UserAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAnalytics", ctx, userID)
	ret0, _ := ret[0].(*UserAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAnalytics indicates an expected call of GetUserAnalytics.
func (mr *MockServiceMockRecorder) GetUserAnalytics(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAnalytics", reflect.TypeOf((*MockService)(nil).GetUserAnalytics), ctx, userID)
}

// ProcessEvent mocks base method.
func (m *MockService) ProcessEvent(ctx context.Context, event *Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessEvent indicates an expected call of ProcessEvent.
func (mr *MockServiceMockRecorder) ProcessEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessEvent", reflect.TypeOf((*MockService)(nil).ProcessEvent), ctx, event)
}
